# Generated by Django 6.0.6 on 2026-06-14 17:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('supplier_invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelBillingConfirmationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmation_no', models.CharField(max_length=36, unique=True)),
                ('supplier_invoice_number', models.CharField(max_length=80)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('matched_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('difference_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('REVIEWED', 'Reviewed'), ('SENT_TO_FINANCE', 'Sent to Finance'), ('FINANCE_ACCEPTED', 'Finance Accepted'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('REVISED', 'Revised')], default='DRAFT', max_length=30)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_finance_at', models.DateTimeField(blank=True, null=True)),
                ('finance_status', models.CharField(choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='NOT_SENT', max_length=20)),
                ('pdf_file', models.FileField(blank=True, upload_to='tbcn/%Y/%m/')),
                ('is_locked', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tbcn', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tbcn', to=settings.AUTH_USER_MODEL)),
                ('sent_to_finance_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tbcn', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_confirmations', to='master_data.supplier')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_confirmations', to='supplier_invoices.supplierinvoice')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelBillingConfirmationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('revised_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('snapshot_json', models.JSONField(blank=True, default=dict)),
                ('original_tbcn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='billing_confirmations.travelbillingconfirmationnote')),
                ('revised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tbcn_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['original_tbcn', 'revision_number'],
            },
        ),
        migrations.AddIndex(
            model_name='travelbillingconfirmationnote',
            index=models.Index(fields=['confirmation_no'], name='billing_con_confirm_04d1e6_idx'),
        ),
        migrations.AddIndex(
            model_name='travelbillingconfirmationnote',
            index=models.Index(fields=['supplier_invoice'], name='billing_con_supplie_a5e841_idx'),
        ),
        migrations.AddIndex(
            model_name='travelbillingconfirmationnote',
            index=models.Index(fields=['finance_status'], name='billing_con_finance_da13ff_idx'),
        ),
        migrations.AddIndex(
            model_name='travelbillingconfirmationnote',
            index=models.Index(fields=['status'], name='billing_con_status_114c04_idx'),
        ),
        migrations.AddConstraint(
            model_name='travelbillingconfirmationnote',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CANCELLED', 'REVISED']), _negated=True), fields=('supplier_invoice',), name='unique_active_tbcn_per_supplier_invoice'),
        ),
        migrations.AddConstraint(
            model_name='travelbillingconfirmationrevision',
            constraint=models.UniqueConstraint(fields=('original_tbcn', 'revision_number'), name='unique_tbcn_revision_number'),
        ),
    ]
