# Generated by Django 6.0.6 on 2026-06-14 17:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('ticket_versions', '0001_initial'),
        ('travel_cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_record_number', models.CharField(max_length=32, unique=True)),
                ('supplier_invoice_number', models.CharField(max_length=80)),
                ('invoice_date', models.DateField()),
                ('received_date', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice_file', models.FileField(blank=True, upload_to='supplier-invoices/%Y/%m/')),
                ('status', models.CharField(choices=[('INVOICE_RECEIVED', 'Invoice Received'), ('DATA_EXTRACTED', 'Data Extracted'), ('AWAITING_MATCHING', 'Awaiting Matching'), ('MATCHED', 'Matched'), ('EXCEPTION_FOUND', 'Exception Found'), ('HR_APPROVED', 'HR Approved'), ('TBCN_GENERATED', 'TBCN Generated'), ('SENT_TO_FINANCE', 'Sent to Finance'), ('FINANCE_ACCEPTED', 'Finance Accepted'), ('PAID', 'Paid'), ('CLOSED', 'Closed')], default='INVOICE_RECEIVED', max_length=30)),
                ('extracted_data_json', models.JSONField(blank=True, default=dict)),
                ('ai_confidence_json', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_supplier_invoices', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_invoices', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='master_data.supplier')),
            ],
            options={
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(max_length=80)),
                ('route_from', models.CharField(blank=True, max_length=80)),
                ('route_to', models.CharField(blank=True, max_length=80)),
                ('booked_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoiced_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('difference_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account_type', models.CharField(choices=[('COMPANY', 'Company'), ('PERSONAL', 'Personal')], max_length=20)),
                ('match_status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('DIFFERENCE', 'Difference'), ('EXCEPTION', 'Exception'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='UNMATCHED', max_length=20)),
                ('exception_reason', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='master_data.employee')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='supplier_invoices.supplierinvoice')),
                ('ticket_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='ticket_versions.ticketversion')),
                ('travel_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='travel_cases.travelcase')),
            ],
            options={
                'ordering': ['supplier_invoice', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['supplier'], name='supplier_in_supplie_19a37a_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['status'], name='supplier_in_status_47b0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['invoice_date'], name='supplier_in_invoice_e7e473_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['received_date'], name='supplier_in_receive_de04fc_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['invoice_record_number'], name='supplier_in_invoice_cd2f53_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(fields=('supplier', 'supplier_invoice_number'), name='unique_supplier_invoice_number_per_supplier'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoiceline',
            index=models.Index(fields=['ticket_number'], name='supplier_in_ticket__fafe4c_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoiceline',
            index=models.Index(fields=['match_status'], name='supplier_in_match_s_6df8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoiceline',
            index=models.Index(fields=['travel_case'], name='supplier_in_travel__0a56eb_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoiceline',
            index=models.Index(fields=['ticket_version'], name='supplier_in_ticket__9b09f6_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoiceline',
            index=models.Index(fields=['supplier_invoice', 'match_status'], name='supplier_in_supplie_cc94df_idx'),
        ),
    ]
