# Generated by Django 6.0.6 on 2026-06-14 17:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_type', models.CharField(choices=[('FLIGHT_TICKET', 'Flight Ticket'), ('CHANGED_TICKET', 'Changed Ticket'), ('REISSUED_TICKET', 'Reissued Ticket'), ('CANCELLATION', 'Cancellation'), ('REFUND_NOTE', 'Refund Note'), ('SUPPLIER_INVOICE', 'Supplier Invoice'), ('PERMIT_DOCUMENT', 'Permit Document'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('source_file', models.FileField(upload_to='ai-extraction/%Y/%m/')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('EXTRACTED', 'Extracted'), ('NEEDS_REVIEW', 'Needs Review'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('raw_extracted_data', models.JSONField(blank=True, default=dict)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('confidence_json', models.JSONField(blank=True, default=dict)),
                ('missing_critical_fields', models.JSONField(blank=True, default=list)),
                ('suggested_matches', models.JSONField(blank=True, default=list)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_extraction_jobs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_extraction_jobs', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_extraction_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiExtractionCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=120)),
                ('original_ai_value', models.JSONField(blank=True, null=True)),
                ('corrected_value', models.JSONField(blank=True, null=True)),
                ('corrected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('correction_reason', models.TextField(blank=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_extraction_corrections', to=settings.AUTH_USER_MODEL)),
                ('extraction_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='ai_extraction.documentextractionjob')),
            ],
            options={
                'ordering': ['-corrected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documentextractionjob',
            index=models.Index(fields=['document_type'], name='ai_extracti_documen_e0495b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentextractionjob',
            index=models.Index(fields=['status'], name='ai_extracti_status_3c3e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentextractionjob',
            index=models.Index(fields=['created_at'], name='ai_extracti_created_dd5ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='aiextractioncorrection',
            index=models.Index(fields=['extraction_job', 'field_name'], name='ai_extracti_extract_e9a6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='aiextractioncorrection',
            index=models.Index(fields=['corrected_by'], name='ai_extracti_correct_f305d1_idx'),
        ),
        migrations.AddIndex(
            model_name='aiextractioncorrection',
            index=models.Index(fields=['corrected_at'], name='ai_extracti_correct_420647_idx'),
        ),
    ]
