# Generated by Django 6.0.6 on 2026-06-14 17:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('case_number', models.CharField(max_length=32, unique=True)),
                ('badge_number', models.CharField(max_length=40)),
                ('employee_name', models.CharField(max_length=180)),
                ('travel_purpose', models.CharField(choices=[('LEAVE_ROTATION', 'Leave Rotation'), ('BUSINESS_TRIP', 'Business Trip'), ('NEW_HIRE', 'New Hire'), ('EMERGENCY', 'Emergency'), ('PERSONAL', 'Personal'), ('OTHER', 'Other')], max_length=30)),
                ('account_type', models.CharField(choices=[('COMPANY', 'Company'), ('PERSONAL', 'Personal')], max_length=20)),
                ('route_from', models.CharField(max_length=80)),
                ('route_to', models.CharField(max_length=80)),
                ('requested_travel_date', models.DateField()),
                ('requested_return_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('current_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED_BY_HR', 'Submitted by HR'), ('UNDER_BOOKING', 'Under Booking'), ('OPTIONS_RECEIVED', 'Options Received'), ('APPROVED_FOR_BOOKING', 'Approved for Booking'), ('TICKET_BOOKED', 'Ticket Booked'), ('CHANGE_REQUESTED', 'Change Requested'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled'), ('INVOICE_RECEIVED', 'Invoice Received'), ('INVOICE_MATCHED', 'Invoice Matched'), ('SENT_TO_FINANCE', 'Sent to Finance'), ('PAID', 'Paid'), ('CLOSED', 'Closed')], default='DRAFT', max_length=30)),
                ('approval_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_travel_cases', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_cases', to='master_data.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_travel_cases', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_cases', to='master_data.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_cases', to='master_data.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_cases', to='master_data.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['current_status'], name='travel_case_current_d180fe_idx'), models.Index(fields=['employee'], name='travel_case_employe_6b283b_idx'), models.Index(fields=['project'], name='travel_case_project_2fc347_idx'), models.Index(fields=['requested_travel_date'], name='travel_case_request_b45426_idx'), models.Index(fields=['account_type'], name='travel_case_account_22fc5a_idx'), models.Index(fields=['case_number'], name='travel_case_case_nu_f19ebd_idx')],
            },
        ),
    ]
