# Generated by Django 6.0.6 on 2026-06-14 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('travel_cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.CharField(max_length=10)),
                ('ticket_action', models.CharField(choices=[('ORIGINAL', 'Original'), ('REISSUE', 'Reissue'), ('DATE_CHANGE', 'Date Change'), ('CANCELLATION', 'Cancellation'), ('REFUND', 'Refund'), ('NO_SHOW', 'No Show'), ('REPLACEMENT', 'Replacement'), ('ADDITIONAL_RETURN', 'Additional Return'), ('WRONG_UPLOAD', 'Wrong Upload')], max_length=30)),
                ('passenger_name', models.CharField(max_length=180)),
                ('ticket_number', models.CharField(max_length=80)),
                ('pnr', models.CharField(max_length=40)),
                ('airline', models.CharField(blank=True, max_length=120)),
                ('route_from', models.CharField(max_length=80)),
                ('route_to', models.CharField(max_length=80)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('ticket_status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CHANGED', 'Changed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('NO_SHOW', 'No Show'), ('LOCKED', 'Locked')], default='DRAFT', max_length=20)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('change_reason', models.TextField(blank=True)),
                ('uploaded_ticket_file', models.FileField(blank=True, upload_to='tickets/%Y/%m/')),
                ('extracted_data_json', models.JSONField(blank=True, default=dict)),
                ('ai_confidence_json', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_ticket_versions', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_versions', to='master_data.supplier')),
                ('travel_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_versions', to='travel_cases.travelcase')),
            ],
            options={
                'ordering': ['travel_case', 'version_number'],
                'indexes': [models.Index(fields=['ticket_number'], name='ticket_vers_ticket__c3d09d_idx'), models.Index(fields=['pnr'], name='ticket_vers_pnr_6df409_idx'), models.Index(fields=['supplier'], name='ticket_vers_supplie_ab0ff6_idx'), models.Index(fields=['departure_date'], name='ticket_vers_departu_0bb0b8_idx'), models.Index(fields=['travel_case', 'ticket_status'], name='ticket_vers_travel__338a80_idx')],
                'constraints': [models.UniqueConstraint(fields=('travel_case', 'version_number'), name='unique_ticket_version_per_case')],
            },
        ),
    ]
