# Generated by Django 6.0.6 on 2026-08-02 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_employee_notes'),
        ('ticket_versions', '0002_ticketversion_currency_choices'),
        ('travel_cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketversion',
            name='billing_state',
            field=models.CharField(choices=[('NOT_BILLABLE', 'Not Billable'), ('AWAITING_INVOICE', 'Awaiting Supplier Invoice'), ('INVOICED', 'Invoiced')], default='NOT_BILLABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketversion',
            name='billing_state_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketversion',
            name='billing_state_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='ticketversion',
            index=models.Index(fields=['billing_state'], name='ticket_vers_billing_648f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketversion',
            index=models.Index(fields=['billing_state', 'supplier'], name='ticket_vers_billing_5204f8_idx'),
        ),
    ]
