# Generated by Django 6.0.6 on 2026-06-14 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='master_data_code_39c339_idx'), models.Index(fields=['name'], name='master_data_name_9dd7ef_idx'), models.Index(fields=['is_active'], name='master_data_is_acti_c4e8c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='master_data_code_990772_idx'), models.Index(fields=['name'], name='master_data_name_d3b613_idx'), models.Index(fields=['is_active'], name='master_data_is_acti_631e0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('cost_center', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='master_data.country')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge_number', models.CharField(max_length=40, unique=True)),
                ('full_name', models.CharField(max_length=180)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='master_data.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='master_data.project')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(max_length=80)),
                ('destination', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='master_data.country')),
            ],
            options={
                'ordering': ['origin', 'destination'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('tax_number', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='master_data_code_48eecf_idx'), models.Index(fields=['name'], name='master_data_name_790ad9_idx'), models.Index(fields=['is_active'], name='master_data_is_acti_b9e8ff_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['code'], name='master_data_code_00be71_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='master_data_name_cb8f22_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['country', 'is_active'], name='master_data_country_61b781_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['badge_number'], name='master_data_badge_n_8bd755_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['full_name'], name='master_data_full_na_5cba68_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['project', 'is_active'], name='master_data_project_70c611_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'is_active'], name='master_data_departm_fe8be2_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['origin'], name='master_data_origin_686170_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['destination'], name='master_data_destina_2dd510_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['country', 'is_active'], name='master_data_country_18ff51_idx'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('origin', 'destination', 'country'), name='unique_route_per_country'),
        ),
    ]
