# Generated by Django 6.0.6 on 2026-06-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
