# Generated by Django 6.0.6 on 2026-06-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['code', 'year'],
                'indexes': [models.Index(fields=['code', 'year'], name='common_cont_code_ea65b6_idx')],
                'constraints': [models.UniqueConstraint(fields=('code', 'year'), name='unique_control_sequence_code_year')],
            },
        ),
    ]
