# Generated by Django 6.0.6 on 2026-06-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOpsUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=180)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('is_travelops_active', models.BooleanField(default=True)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travelops_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'indexes': [models.Index(fields=['is_travelops_active'], name='access_cont_is_trav_dd9636_idx'), models.Index(fields=['is_super_admin'], name='access_cont_is_supe_0804b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAccessScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global'), ('COUNTRY', 'Country'), ('PROJECT', 'Project'), ('DEPARTMENT', 'Department')], max_length=20)),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_finance', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_scopes', to='master_data.country')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_scopes', to='master_data.department')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_scopes', to='master_data.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'scope_type', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='access_cont_user_id_5a131a_idx'), models.Index(fields=['scope_type'], name='access_cont_scope_t_801e88_idx'), models.Index(fields=['country'], name='access_cont_country_cee265_idx'), models.Index(fields=['project'], name='access_cont_project_ae087a_idx'), models.Index(fields=['department'], name='access_cont_departm_e8abca_idx')],
            },
        ),
    ]
