# Generated by Django 6.0.6 on 2026-06-14 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel_cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permit_type', models.CharField(choices=[('EGYPT_PERMIT', 'Egypt Permit'), ('LIBYA_PERMIT', 'Libya Permit')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('NOT_REQUIRED', 'Not Required')], default='PENDING', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, upload_to='permits/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permits', to=settings.AUTH_USER_MODEL)),
                ('travel_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='travel_cases.travelcase')),
            ],
            options={
                'ordering': ['travel_case', 'permit_type'],
                'indexes': [models.Index(fields=['permit_type'], name='permits_per_permit__77b6e3_idx'), models.Index(fields=['status'], name='permits_per_status_6c419b_idx'), models.Index(fields=['expiry_date'], name='permits_per_expiry__bbf069_idx')],
                'constraints': [models.UniqueConstraint(fields=('travel_case', 'permit_type'), name='unique_permit_type_per_case')],
            },
        ),
    ]
